package formularios;

// Generated 17-feb-2012 0:41:27 by Hibernate Tools 3.4.0.CR1

/**
 * Equipos generated by hbm2java
 */
public class formEquipo implements java.io.Serializable {
	private Integer idEquipo;
	private String nombre;
	private String estadio;
	private Integer idUsuarioFk;

	public formEquipo() {
	}

	public formEquipo(String nombre, String estadio, Integer idUsuarioFk) {
		this.nombre = nombre;
		this.estadio = estadio;
		this.idUsuarioFk = idUsuarioFk;
	}

	public Integer getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstadio() {
		return this.estadio;
	}

	public void setEstadio(String estadio) {
		this.estadio = estadio;
	}

	public Integer getIdUsuarioFk() {
		return this.idUsuarioFk;
	}

	public void setIdUsuarioFk(Integer idUsuarioFk) {
		this.idUsuarioFk = idUsuarioFk;
	}

}
