package formularios;

// Generated 25-ene-2012 12:17:36 by Hibernate Tools 3.4.0.CR1

/**
 * Usuarios generated by hbm2java
 */
public class formUsuario implements java.io.Serializable {

	/**
	 * serializable
	 */
	private static final long serialVersionUID = 1L;
	
	private String nombre;
	private String apellidos;
	private String email;
	private String usuario;
	private String password;
	private String direccion;
	private boolean sexo;

	public formUsuario() {
		this.nombre = null;
		this.apellidos = null;
		this.email = null;
		this.usuario = null;
		this.password = null;
		this.direccion = null;
		this.sexo = false;
	}

	
	

	public formUsuario(String nombre, String apellidos, String email,
			String usuario, String password, String direccion, boolean sexo) {
		super();
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.usuario = usuario;
		this.password = password;
		this.direccion = direccion;
		this.sexo = sexo;
	}




	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public boolean getSexo() {
		return this.sexo;
	}

	public void setSexo(boolean sexo) {
		this.sexo = sexo;
	}




	public String getEmail() {
		return email;
	}




	public void setEmail(String email) {
		this.email = email;
	}

}
