package modelos;

// Generated 21-feb-2012 17:01:18 by Hibernate Tools 3.4.0.CR1

/**
 * FrecuenciaNacionalidad generated by hbm2java
 */
public class FrecuenciaNacionalidad implements java.io.Serializable {

	private Integer idFrecNac;
	private Integer idNombreFk;
	private Integer idNacionalidadFk;
	private Integer frecuenciaNombre;

	public FrecuenciaNacionalidad() {
	}

	public FrecuenciaNacionalidad(Integer idNombreFk, Integer idNacionalidadFk,
			Integer frecuenciaNombre) {
		this.idNombreFk = idNombreFk;
		this.idNacionalidadFk = idNacionalidadFk;
		this.frecuenciaNombre = frecuenciaNombre;
	}

	public Integer getIdFrecNac() {
		return this.idFrecNac;
	}

	public void setIdFrecNac(Integer idFrecNac) {
		this.idFrecNac = idFrecNac;
	}

	public Integer getIdNombreFk() {
		return this.idNombreFk;
	}

	public void setIdNombreFk(Integer idNombreFk) {
		this.idNombreFk = idNombreFk;
	}

	public Integer getIdNacionalidadFk() {
		return this.idNacionalidadFk;
	}

	public void setIdNacionalidadFk(Integer idNacionalidadFk) {
		this.idNacionalidadFk = idNacionalidadFk;
	}

	public Integer getFrecuenciaNombre() {
		return this.frecuenciaNombre;
	}

	public void setFrecuenciaNombre(Integer frecuenciaNombre) {
		this.frecuenciaNombre = frecuenciaNombre;
	}

}
