package modelos;

// Generated 21-feb-2012 17:01:18 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FrecNacApellidos generated by hbm2java
 */
public class FrecNacApellidos implements java.io.Serializable {

	private Integer idFrecNacApellidos;
	private Integer idApellidosFk;
	private Integer idNacionalidadFk;
	private BigDecimal frecuenciaApellido;

	public FrecNacApellidos() {
	}

	public FrecNacApellidos(Integer idApellidosFk, Integer idNacionalidadFk,
			BigDecimal frecuenciaApellido) {
		this.idApellidosFk = idApellidosFk;
		this.idNacionalidadFk = idNacionalidadFk;
		this.frecuenciaApellido = frecuenciaApellido;
	}

	public Integer getIdFrecNacApellidos() {
		return this.idFrecNacApellidos;
	}

	public void setIdFrecNacApellidos(Integer idFrecNacApellidos) {
		this.idFrecNacApellidos = idFrecNacApellidos;
	}

	public Integer getIdApellidosFk() {
		return this.idApellidosFk;
	}

	public void setIdApellidosFk(Integer idApellidosFk) {
		this.idApellidosFk = idApellidosFk;
	}

	public Integer getIdNacionalidadFk() {
		return this.idNacionalidadFk;
	}

	public void setIdNacionalidadFk(Integer idNacionalidadFk) {
		this.idNacionalidadFk = idNacionalidadFk;
	}

	public BigDecimal getFrecuenciaApellido() {
		return this.frecuenciaApellido;
	}

	public void setFrecuenciaApellido(BigDecimal frecuenciaApellido) {
		this.frecuenciaApellido = frecuenciaApellido;
	}

}
