package modelos;

// Generated 21-feb-2012 17:01:18 by Hibernate Tools 3.4.0.CR1

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores implements java.io.Serializable {

	private Integer idJugador;
	private String nombre;
	private String apellidos;
	private String descripcion;
	private String social;
	private String posicion;
	private String altura;
	private Integer edad;
	private Integer idCaracteristicasFk;
	private Integer idEquipoFk;
	private Integer sueldo;

	public Jugadores() {
	}

	public Jugadores(String nombre, String apellidos, String descripcion,
			String social, String posicion, String altura, Integer edad,
			Integer idCaracteristicasFk, Integer idEquipoFk, Integer sueldo) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.descripcion = descripcion;
		this.social = social;
		this.posicion = posicion;
		this.altura = altura;
		this.edad = edad;
		this.idCaracteristicasFk = idCaracteristicasFk;
		this.idEquipoFk = idEquipoFk;
		this.sueldo = sueldo;
	}

	public Integer getIdJugador() {
		return this.idJugador;
	}

	public void setIdJugador(Integer idJugador) {
		this.idJugador = idJugador;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getSocial() {
		return this.social;
	}

	public void setSocial(String social) {
		this.social = social;
	}

	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	public String getAltura() {
		return this.altura;
	}

	public void setAltura(String altura) {
		this.altura = altura;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public Integer getIdCaracteristicasFk() {
		return this.idCaracteristicasFk;
	}

	public void setIdCaracteristicasFk(Integer idCaracteristicasFk) {
		this.idCaracteristicasFk = idCaracteristicasFk;
	}

	public Integer getIdEquipoFk() {
		return this.idEquipoFk;
	}

	public void setIdEquipoFk(Integer idEquipoFk) {
		this.idEquipoFk = idEquipoFk;
	}

	public Integer getSueldo() {
		return this.sueldo;
	}

	public void setSueldo(Integer sueldo) {
		this.sueldo = sueldo;
	}

}
