package modelos;

// Generated 21-feb-2012 17:01:18 by Hibernate Tools 3.4.0.CR1

/**
 * Nombres generated by hbm2java
 */
public class Nombres implements java.io.Serializable {

	private Integer idNombre;
	private String nombre;

	public Nombres() {
	}

	public Nombres(String nombre) {
		this.nombre = nombre;
	}

	public Integer getIdNombre() {
		return this.idNombre;
	}

	public void setIdNombre(Integer idNombre) {
		this.idNombre = idNombre;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
