package modelos;

// Generated 21-feb-2012 17:01:18 by Hibernate Tools 3.4.0.CR1

/**
 * Apellidos generated by hbm2java
 */
public class Apellidos implements java.io.Serializable {

	private Integer idApellido;
	private String apellido;

	public Apellidos() {
	}

	public Apellidos(String apellido) {
		this.apellido = apellido;
	}

	public Integer getIdApellido() {
		return this.idApellido;
	}

	public void setIdApellido(Integer idApellido) {
		this.idApellido = idApellido;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

}
