package modelos;

// Generated 21-feb-2012 17:01:18 by Hibernate Tools 3.4.0.CR1

/**
 * Caracteristicas generated by hbm2java
 */
public class Caracteristicas implements java.io.Serializable {

	private Integer idCaracteristica;
	private Integer tecnica;
	private Integer velocidad;
	private Integer rebote;
	private Integer pase;
	private Integer tiro;
	private Integer fuerza;
	private Integer asistencia;
	private Integer robo;
	private Integer estrategia;
	private Integer idJugadorFk;

	public Caracteristicas() {
	}

	public Caracteristicas(Integer tecnica, Integer velocidad, Integer rebote,
			Integer pase, Integer tiro, Integer fuerza, Integer asistencia,
			Integer robo, Integer estrategia, Integer idJugadorFk) {
		this.tecnica = tecnica;
		this.velocidad = velocidad;
		this.rebote = rebote;
		this.pase = pase;
		this.tiro = tiro;
		this.fuerza = fuerza;
		this.asistencia = asistencia;
		this.robo = robo;
		this.estrategia = estrategia;
		this.idJugadorFk = idJugadorFk;
	}

	public Integer getIdCaracteristica() {
		return this.idCaracteristica;
	}

	public void setIdCaracteristica(Integer idCaracteristica) {
		this.idCaracteristica = idCaracteristica;
	}

	public Integer getTecnica() {
		return this.tecnica;
	}

	public void setTecnica(Integer tecnica) {
		this.tecnica = tecnica;
	}

	public Integer getVelocidad() {
		return this.velocidad;
	}

	public void setVelocidad(Integer velocidad) {
		this.velocidad = velocidad;
	}

	public Integer getRebote() {
		return this.rebote;
	}

	public void setRebote(Integer rebote) {
		this.rebote = rebote;
	}

	public Integer getPase() {
		return this.pase;
	}

	public void setPase(Integer pase) {
		this.pase = pase;
	}

	public Integer getTiro() {
		return this.tiro;
	}

	public void setTiro(Integer tiro) {
		this.tiro = tiro;
	}

	public Integer getFuerza() {
		return this.fuerza;
	}

	public void setFuerza(Integer fuerza) {
		this.fuerza = fuerza;
	}

	public Integer getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Integer asistencia) {
		this.asistencia = asistencia;
	}

	public Integer getRobo() {
		return this.robo;
	}

	public void setRobo(Integer robo) {
		this.robo = robo;
	}

	public Integer getEstrategia() {
		return this.estrategia;
	}

	public void setEstrategia(Integer estrategia) {
		this.estrategia = estrategia;
	}

	public Integer getIdJugadorFk() {
		return this.idJugadorFk;
	}

	public void setIdJugadorFk(Integer idJugadorFk) {
		this.idJugadorFk = idJugadorFk;
	}

}
