package modelos;

// Generated 21-feb-2012 17:01:18 by Hibernate Tools 3.4.0.CR1

/**
 * Equipos generated by hbm2java
 */
public class Equipos implements java.io.Serializable {

	private Integer idEquipo;
	private String nombre;
	private String estadio;
	private Integer idUsuarioFk;
	private Integer numJugadores;

	public Equipos() {
	}

	public Equipos(String nombre, String estadio, Integer idUsuarioFk,
			Integer numJugadores) {
		this.nombre = nombre;
		this.estadio = estadio;
		this.idUsuarioFk = idUsuarioFk;
		this.numJugadores = numJugadores;
	}

	public Integer getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstadio() {
		return this.estadio;
	}

	public void setEstadio(String estadio) {
		this.estadio = estadio;
	}

	public Integer getIdUsuarioFk() {
		return this.idUsuarioFk;
	}

	public void setIdUsuarioFk(Integer idUsuarioFk) {
		this.idUsuarioFk = idUsuarioFk;
	}

	public Integer getNumJugadores() {
		return this.numJugadores;
	}

	public void setNumJugadores(Integer numJugadores) {
		this.numJugadores = numJugadores;
	}

}
