package modelos;

// Generated 21-feb-2012 17:01:18 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FrecNacNombre generated by hbm2java
 */
public class FrecNacNombre implements java.io.Serializable {

	private Integer idFrecNac;
	private Integer idNombreFk;
	private Integer idNacionalidadFk;
	private BigDecimal frecuenciaNombre;
	private Integer cantidad;

	public FrecNacNombre() {
	}

	public FrecNacNombre(Integer idNombreFk, Integer idNacionalidadFk,
			BigDecimal frecuenciaNombre, Integer cantidad) {
		this.idNombreFk = idNombreFk;
		this.idNacionalidadFk = idNacionalidadFk;
		this.frecuenciaNombre = frecuenciaNombre;
		this.cantidad = cantidad;
	}

	public Integer getIdFrecNac() {
		return this.idFrecNac;
	}

	public void setIdFrecNac(Integer idFrecNac) {
		this.idFrecNac = idFrecNac;
	}

	public Integer getIdNombreFk() {
		return this.idNombreFk;
	}

	public void setIdNombreFk(Integer idNombreFk) {
		this.idNombreFk = idNombreFk;
	}

	public Integer getIdNacionalidadFk() {
		return this.idNacionalidadFk;
	}

	public void setIdNacionalidadFk(Integer idNacionalidadFk) {
		this.idNacionalidadFk = idNacionalidadFk;
	}

	public BigDecimal getFrecuenciaNombre() {
		return this.frecuenciaNombre;
	}

	public void setFrecuenciaNombre(BigDecimal frecuenciaNombre) {
		this.frecuenciaNombre = frecuenciaNombre;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
