package modelos;

// Generated 21-feb-2012 17:01:18 by Hibernate Tools 3.4.0.CR1

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer idUsuario;
	private String nombre;
	private String apellidos;
	private String usuario;
	private String password;
	private String direccion;
	private Character sexo;
	private Integer idEquipoFk;

	public Usuarios() {
	}

	public Usuarios(String nombre, String apellidos, String usuario,
			String password, String direccion, Character sexo,
			Integer idEquipoFk) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.usuario = usuario;
		this.password = password;
		this.direccion = direccion;
		this.sexo = sexo;
		this.idEquipoFk = idEquipoFk;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Character getSexo() {
		return this.sexo;
	}

	public void setSexo(Character sexo) {
		this.sexo = sexo;
	}

	public Integer getIdEquipoFk() {
		return this.idEquipoFk;
	}

	public void setIdEquipoFk(Integer idEquipoFk) {
		this.idEquipoFk = idEquipoFk;
	}

}
